### ISSUE TITLE
php 5.4+ support?

### ISSUE THREAD

**Issue by grom358** [rlerdorf/phan#1]
This is so awesome. I have also been working towards this but for PHP 5. Currently I have the following pieces:
- PHP Syntax tree - http://github.com/grom358/pharborist
- Static Reflection - https://github.com/grom358/php-static-reflection

I am looking at using Zephir/PHP-CPP to port pharborist to PHP extension for performance reasons to build an analysis tool on. But I see you already got a lot of effort done on the actual static analysis part so I was thinking be good if we can share efforts somehow that would be awesome. How coupled is it to the nikic AST extension? Maybe could create a standard AST API so I could make my extension for php 5 work with your project.

Also are you aware of https://github.com/JetBrains/phpstorm-stubs . It has a lot of the stubs. The files are not exactly organised the best... I don't have a repo yet but I had used that as base to create a file per each core part of php as it is in the manual. That is I have a strings.php that contains the signatures as per http://php.net/manual/en/ref.strings.php etc. Then I can load up definitions as per extensions that are loaded.

**Comment by rlerdorf** [comment]
It is very coupled to the PHP 7 AST.

The JetBrains stubs seems to just be a crawl of the manual. It would be easier to just grab http://svn.php.net/repository/phpdoc/doc-base/trunk/funcsummary.txt if that is what you want.
I am aiming to cover more cases with union types and alternate signatures in arginfo.php.

In the end, arginfo.php is likely the only part of this project that will survive the test of time. At least if my plan goes as expected. I don't want to be maintaining a static analysis project.
