### ISSUE TITLE
Is there a way to ignore type errors?

### ISSUE THREAD

**Issue by messyOne** [rlerdorf/phan#10]
I want to ignore TypeError messages. Is there a way to specify which errors shall be shown?

**Comment by rlerdorf** [comment]
Very simple to add a flag for that. See the -i flag which is implemented like this in includes/cli.php:

```
        case 'i':
        Log::setOutputMask(Log::getOutputMask()^Log::EUNDEF);
        break;
```

**Comment by messyOne** [comment]
Works like a charm. Thanks.
