### ISSUE TITLE
mtkime false positives?

### ISSUE THREAD

**Issue by christopherowen** [rlerdorf/phan#16]
the following code produces an error

```
$month_text = date('F', mktime(0, 0, 0, $_REQUEST['rMonth'], date("d"), $_REQUEST['rYear']));
```

of:

```
TypeError arg#5(day) is string but mktime() takes int
```

but date("d") does return an integer.

**Comment by rlerdorf** [comment]
No it doesn't.

php > var_dump(date('d'));
string(2) "16"

**Comment by christopherowen** [comment]
Thank you for showing me the technique; I learned something new.  I will cast the output of date("d") to int.
